semi_shop/noon/api/urls.py
from django.urls import path
from .views import index,get_product


urlpatterns = [

   path("",index),
   path("<int:id>/",get_product)


]

semi_shop/noon/urls.py
from django.contrib import admin
from django.urls import path,include
from noon.views import contact, about,products,show_product ,delete,search,create,update

urlpatterns = [

    path("",products,name="noon2.products"),
    path("show_product/<int:id>" ,show_product,name="noon2.show_product"),
    path("contact" ,contact,name="noon.contant"),
    path("about" ,about,name="noon.about"),
    path('<int:id>/delete',delete,name="noon.delete"),
    path('search',search,name="noon.search"),
    path('create',create,name="noon.create"),
    path('update/<int:id>',update,name="noon.update"),
    path('api/',include('noon.api.urls'))
 
]

semi_shop/semi_shop/urls.py
from django.contrib import admin
from django.urls import path ,include
# from semi_amazon.views import 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("" ,include('noon.urls')),
    path("category/" ,include('category.urls')),
    path("accounts/" ,include('accounts.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

semi_shop/noon/models.py
from django.db import models 
from category.models import Category
from django.shortcuts import  reverse
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=400 ,null=True)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    stock = models.IntegerField(default=0 ,null=True)
    image = models.ImageField (upload_to="noon/images", null=True,blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, null=True, blank=True,on_delete=models.CASCADE,related_name="product")
    owner = models.ForeignKey(User, null=True, blank=True,
                              on_delete=models.CASCADE, related_name='owner')


    def __str__(self):
        return f"{self.title }"

    @classmethod
    def get_all(cls):
        return cls.objects.all()
    
    def get_image_url(self):
        return f"/media/{self.image}"

    def get_show_url(self):
        return  reverse('noon2.show_product', args=[self.id])


    def get_delete_url(self):
        return  reverse('noon.delete', args=[self.id])
    
    def update (self):
        return reverse("noon.update", args  = [self.id])


    

semi_shop/noon/forms.py
from django import forms
from category.models import Category


class ProductForm(forms.Form):
    title = forms.CharField(label='Product title')
    description = forms.CharField()
    price = forms.DecimalField()
    stock = forms.IntegerField()
    image = forms.ImageField ()
    category = forms.ModelChoiceField(Category.get_all(), required=False)

    

semi_shop/noon/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializer import ProductSerializer  
from noon.models import Product

@api_view(['GET', 'POST'])
def index(request):
    if request.method == 'POST':
        product = ProductSerializer(data=request.data)
        if product.is_valid():
            product.save()
            return Response({'message': 'Product is successfully received', 'product': product.data}, status=201)
        else:
            return Response(product.errors, status=400)

    elif request.method == 'GET':
        products = Product.objects.all()
        serialized_products = ProductSerializer(products, many=True).data

        return Response({'message': 'data received', 'products': serialized_products})

@api_view(['GET',"DELETE","PUT"])
def get_product(request,id):
    product=Product.objects.filter(id=id).first()
    if request.method == 'GET':
        serialized_item = ProductSerializer(product)
        return Response({'message': 'data received', 'product':serialized_item.data}, status=200)

    elif request.method =="DELETE":
        product.delete()
        return Response({'message': 'product deleted'}, status=205)
     
    elif request.method=="PUT":
        serialized_item = ProductSerializer(instance=product,data=request.data)
        if serialized_item.is_valid():
            serialized_item.save()
            return Response({'message': 'product saved', 'data': serialized_item.data}, status=201)
        return Response(serialized_item.errors ,status=401)
    

semi_shop/noon/views.py
from django.shortcuts import render,redirect ,reverse,get_object_or_404
from django.http import HttpResponse 
from noon.models import Product
from noon.forms import ProductForm 
from category.models import Category
from django.contrib.auth.decorators import login_required


def products (request):
    # products = Product.objects.all()
    products=Product.get_all()
    return render(request, "noon2/products.html",context={"products":products})

def show_product(request,id):
    product = get_object_or_404(Product ,pk=id)
    return render (request, "noon2/show_product.html",context={"product":product})

@login_required()
def delete(request,id):
    product = Product.objects.get(id=id)
    product.delete()
    url =reverse("noon2.products")
   
    return redirect(url) 


def contact (request):
    return render( request,"noon2/contact.html")

def about (request):
      return render( request,"noon2/about.html")

def search (request):
    text=request.POST.get('search')
    if text :
        data= Product.objects.filter(title__istartswith=text)
        list(data)
        return render( request,"noon2/search.html",context={"data":data ,"text":text})

@login_required()
def create(request):
    form=ProductForm()
    if request.POST:
        form= ProductForm(request.POST,request.FILES)
        if form.is_valid():
            title=request.POST['title']
            description=request.POST['description']
            price=request.POST['price']
            stock=request.POST['stock']
            category = form.cleaned_data['category']
            image=None
            owner=request.user
            if "image" in request.FILES:
                image=request.FILES['image']
            product = Product.objects.create(title=title,description=description,price=price,stock=stock,image=image,category=category,owner=owner)

            return redirect(product.get_show_url())
    return render( request,"noon2/create.html",context={"form":form})


@login_required()
def update(request, id):
    product = get_object_or_404(Product, id=id)
    categories = Category.objects.all()

    if request.method == 'POST':
        product.title = request.POST.get('title')
        product.description = request.POST.get('description')
        product.price = request.POST.get('price')
        product.stock = request.POST.get('stock')

        # Handle image upload
        image = request.FILES.get('image')
        if image:
            product.image = image

        # Get the Category object for the selected category
        category = request.POST.get('category')
        category_object = Category.objects.get(name=category)

        # Assign the Category object to the product
        product.category = category_object

        product.save()

        return redirect('noon2.show_product', id=id)

    else:
        context = {
            'product': product,
            'categories': categories,
        }
        return render(request, 'noon2/update.html', context)

semi_shop/noon/templates/noon2/about.html
{% extends 'noon2/base.html' %}
{% load static %}
{% block title %} noon enhance {% endblock %}

{% block body %}
<h1> about me</h1>

{% endblock %}

semi_shop/noon/templates/noon2/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'noon/bootstrap/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'noon/bootstrap/css/bootstrap.min.css'%}">
    <style>
        li {
            color: red;
        }
        .text-truncate{
            max-width:350px ;

        }
    </style>
</head>

<body style="position: relative;">
    <div style="position: relative ; min-height: 90vh;">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-warning px-5">
                <div class="container-fluid">
                    <a class="navbar-brand bg-warning" href='{% url "noon2.products" %}'>noon enhance</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page"
                                    href='{% url "noon2.products" %}'>Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'noon.category'   %}">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'noon.about' %}">about me</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'noon.contant' %}">contact me</a>
                            </li>


                        </ul>
                        <form class="d-flex" method="post" action="{% url 'noon.search' %}">
                            {% csrf_token %}
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                                name="search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                        {% if user.id %}
                        <div class="d-flex  mx-3 my-auto">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account.profile2' %}">{{user.username}}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                                </li>
                            </ul>
                        </div>
                        {% else %}
                        <div class="d-flex  mx-3 my-auto">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'accounts.create' %}">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'login' %}">login</a>
                                </li>

                            </ul>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            {% block body %}

            {% endblock %}
            {% block show %}
            {% endblock %}
        </div>



    </div>
    <footer class="mt-5 fs-5 bg-warning p-auto" style=" text-align: center;height: 50px ;position:relative;top: 100 ;">
        <p class="my-auto">copyrights@noon-noon.com</p>
    </footer>
    <script src="{% static 'noon/bootstrap/js/bootstrap.js'%}">

    </script>
    <script src="{% static 'noon/js/script.js' %}">

    </script>
</body>

</ht

semi_shop/noon/templates/noon2/contact.html
{% extends 'noon2/base.html' %}
{% load static %}
{% block title %} noon enhance {% endblock %}

{% block body %}
<h1>contact me</h1>

{% endblock %}

semi_shop/noon/templates/noon2/create.html
{% extends 'noon2/base.html' %}
{% load static %}
{% block title %} noon enhance {% endblock %}

{% block body %}

<h1> Add new Products </h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form}}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<script src="{% static  'noon/js/script.js' %}">

</script>
{% endblock %}

semi_shop/noon/templates/noon2/products.html
{% extends 'noon2/base.html' %}
{% load static %}
{% block title %} noon enhance {% endblock %}

{% block body %}

<!-- {{products}} -->


<h2 class="mt-5 me-3">Welcome to our store</h2>
<hr>
<a class="btn btn-warning mx-auto my-5" href="{% url 'noon.create' %}">Add new Products</a>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for item in products %}
    <div class="col shadow p-2">
        <div class="card h-100">
            <img src="{{item.get_image_url}}" class="card-img-top h-75 shadow" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{item.title}}</h5>
                <p class="card-text text-truncate">{{item.description}}</p>
                <p class="card-text ">category: {{item.category}}</p>
                <p class="card-text">owner: {{item.owner}}</p>
            </div>
            <div class="d-flex justify-content-evenly">
            <a class="btn btn-outline-success my-3 " href="{%  url  'noon2.show_product' item.id %}"> show
                details</a>
            {% if user.id == item.owner.id%}
            <a class="btn btn-outline-danger my-3  " href="{% url 'noon.delete' item.id %}"> Delete</a>
            <a class="btn btn-outline-info my-3 " href="{{item.update}}"> UPDATE</a>
            {% endif %}
        </div>
            <div class="card-footer">
                <small class="text-body-secondary">update_at : {{item.update_at}}</small>
            </div>
        </div>
    </div>

    <!-- </div> -->


    {% endfor %}
</div>



{% endblock %}

semi_shop/noon/templates/noon2/search.html
{% extends 'noon2/base.html' %}
{% load static %}
{% block title %} noon enhance {% endblock %}

{% block body %}
<h2 class="mt-5 me-3">Search Results for: {{text}} </h2>
<hr>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for item in data %}
    <div class="col shadow p-2">
        <div class="card h-100">
            <img src="{{item.get_image_url}}" class="card-img-top h-75 shadow" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{item.title}}</h5>
                <p class="card-text text-truncate">{{item.description}}</p>
                <p class="card-text ">category: {{item.category}}</p>
                <p class="card-text">owner: {{item.owner}}</p>
            </div>
            <div class="d-flex justify-content-evenly">
            <a class="btn btn-outline-success my-3 " href="{%  url  'noon2.show_product' item.id %}"> show
                details</a>
            {% if user.id == item.owner.id%}
            <a class="btn btn-outline-danger my-3  " href="{% url 'noon.delete' item.id %}"> Delete</a>
            <a class="btn btn-outline-info my-3 " href="{{item.update}}"> UPDATE</a>
            {% endif %}
        </div>
            <div class="card-footer">
                <small class="text-body-secondary">update_at : {{item.update_at}}</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

semi_shop/noon/templates/noon2/show_product.html
{% extends 'noon2/base.html' %}
{% load static %}
{% block title %} noon enhance {% endblock %}

{% block body %}
<div class="card  mt-5" style="max-width: 80%;">
    <div class="row g-0">
        <div class="col-md-5 my-auto ">
            <img src="{{product.get_image_url}}" class="img-fluid rounded-start p-2 shadow" alt="...">
        </div>
        <div class="col-md-7">
            <div class="card-body ms-3  d-flex flex-column">
                <h5 class="card-title">{{product.title}}</h5>
                <p class="card-text"><strong>description:</strong> {{product.description}}</p>
                <p class="card-text"><strong>price:</strong> {{product.price}}$</p>
                <p class="card-text"><strong>owner:</strong> {{product.owner.username}}</p>
                {% if product.stock > 0 %}
                <div class="d-flex ">
                    <p class="item-overview text-body-secondary  btn btn-outline-success"> instock</p>
                    <p
                        class="item-overview text-body-secondary border  border-success border-2 ms-5 rounded-3 px-3 py-1">
                        left:{{product.stock}} items</p>

                </div>
                {% else %}
                <p class="item-overview text-body-secondary btn btn-outline-danger my-3"> out of stock</p>
                {% endif %}

                <div class="d-flex justify-items-center flex-column"><a class="btn btn-success w-75 my-2 p-1 mx-auto" href="{%  url  'noon2.products' %}">home </a>

          
                {% if user.id == product.owner.id%}
            <a class="btn btn-info w-75 my-2 p-1 mx-auto" href="{{ product.update }}">update </a></div>
                {% endif %}
                <p class="card-text"><small class="text-body-secondary">update_at : {{product.update_at}}</small></p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

semi_shop/noon/templates/noon2/update.html
{% extends 'noon2/base.html' %}
{% load static %}
{% block title %}Update Product - Noon Enhance{% endblock %}

{% block body %}

<h1>Update Product</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="id_title" class="form-label">Product title:</label>
  <input type="text" name="title" required="" id="id_title" class="form-control" value="{{ product.title }}">

  <label for="id_description" class="form-label">Description:</label>

  <input type="text" name="description" required="" id="id_description" value="{{ product.description }}"
    class="form-control">


  <label for="id_price" class="form-label">Price:</label>


  <input type="number" name="price" step="any" required="" id="id_price" value="{{ product.price }}"
    class="form-control">


  <label for="id_stock" class="form-label">Stock:</label>


  <input type="number" name="stock" required="" id="id_stock" value="{{ product.stock }}" class="form-control">


  <label for="id_image" class="form-label">Image:</label>


  <input type="file" name="image" accept="image/*" required="" id="id_image" value="{{ product.image.url }}"
    class="form-control">
  {% if product.image %}
  <img src="{{ product.image.url }}" alt="{{ product.title }}" width="150">
  {% endif %}


  <label for="id_category" class="form-label">Category:</label>


  <select name="category" id="category" class="form-control" select="">
    {% for category in categories %}
    <option>
      {{ category }}
    </option>
    {% endfor %}
  </select>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>


<script src="{% static 'noon/js/script.js' %}"></script>

{% endblock %}